---
title: Exploratory Data Analysis
subtitle: Pandemic PACT Funding Tracker Dataset
author:
  - name: Ernest Guevarra
    orcid: 0000-0002-4887-4415
    email: ernest.guevarra@ndm.ox.ac.uk
    affiliation: 
      - name: University of Oxford
        city: Oxford
  - name: Proochista Ariana
    email: proochista.ariana@ndm.ox.ac.uk
    affiliation:
      - name: University of Oxford
        city: Oxford
date: "`r format(Sys.Date(), '%d %B %Y')`"
format: 
  html:
    toc: true
    toc-location: left
    embed-resources: true
---

```{r setup}
#| echo: false

targets::tar_load(
  c(disease_year_grant_number_plot, disease_year_grant_amount_plot,
    disease_grant_number_plot, disease_grant_amount_plot,
    category_grant_number_plot, category_grant_amount_plot,
    subcategory_grant_number_plot, subcategory_grant_amount_plot,
    pact_region_funder_table, pact_country_funder_table,
    pact_region_institution_table, pact_country_institution_table,
    pact_region_research_table, pact_country_research_table
   )
)
```

## Grants by disease over time

```{r disease-year-number}
#| echo: false
#| warning: false
#| fig.align: center
#| fig.width: 12
#| fig.height: 12

disease_year_grant_number_plot
```

```{r disease-year-amount}
#| echo: false
#| warning: false
#| fig.align: center
#| fig.width: 12
#| fig.height: 12

disease_year_grant_amount_plot
```

## Grants by disease

```{r disease-number}
#| echo: false
#| warning: false
#| fig.align: center
#| fig.width: 10
#| fig.height: 8

disease_grant_number_plot
```

```{r disease-amount}
#| echo: false
#| warning: false
#| fig.align: center
#| fig.width: 10
#| fig.height: 8

disease_grant_amount_plot
```

## Research categories

```{r category-grant-number}
#| echo: false
#| warning: false
#| fig.height: 10
#| fig.align: center

category_grant_number_plot
```

```{r category-grant-amount}
#| echo: false
#| warning: false
#| fig.height: 10
#| fig.align: center

category_grant_amount_plot
```

## Research subcategories

```{r subcategory-grant-number}
#| echo: false
#| warning: false
#| fig.height: 50
#| fig.weight: 15
#| fig.align: center

subcategory_grant_number_plot
```

```{r subcategory-grant-amount}
#| echo: false
#| warning: false
#| fig.height: 50
#| fig.weight: 15
#| fig.align: center

subcategory_grant_amount_plot
```

## Grants by location

### Grants by funder region

There seems to be a discrepancy between the
